language: php

php:
  - 5.4
  - 5.5

before_install:
  - composer self-update
  - composer update
  - composer install --dev --no-interaction

before_script:
  - cd tests

script:
  - phpunit

after_script:
  - php vendor/bin/coveralls -v
 
notifications:
   email: a.fiori@cheapnet.it
